spring:
  profiles:
    active: dev
# security配置
security:
  # 排除路径
  excludes:
    # 静态资源
    - /*.html
    - /**/*.html
    - /**/*.css
    - /**/*.js
    # 公共路径
    - /favicon.ico
    - /error
    # swagger 文档配置
    - /*/api-docs
    - /*/api-docs/**
    # actuator 监控配置
    - /actuator
    - /actuator/**
# aaa
#启动命令for spark 1.5.1 （指定hadoop、spark、hive、hbase库加载位置，以及xml配置加载位置）
#java -XX:PermSize=512m -XX:MaxPermSize=10240m -Xms1024m -Xmx10240m -Dloader.path="hadoop/conf,hadoop/lib" -Djava.library.path=$HADOOP_PREFIX/lib:$HADOOP_PREFIX/lib/native -Djava.io.tmpdir=./temp/ -jar lambda-manager-1.0.0.jar

#启动命令for spark 2.1.0 （指定hadoop、spark、hive、hbase库加载位置，以及xml配置加载位置）
#java -XX:PermSize=512m -XX:MaxPermSize=10240m -Xms1024m -Xmx10240m -Dloader.path="hadoop/conf,hadoop/lib" -Djava.library.path=$HADOOP_PREFIX/lib:$HADOOP_PREFIX/lib/native -Djava.io.tmpdir=./temp/ -jar lambda-manager-1.0.0.jar

